// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTuffrVXSBtef9ibkP8mLC6oFpdw-pK-o',
    appId: '1:110037213358:android:021ee32e3c5a1a0f2bcd3f',
    messagingSenderId: '110037213358',
    projectId: 'learningfirebase-1262f',
    storageBucket: 'learningfirebase-1262f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBcFwD6DXPT1ITDMv6EH3O4l2t30DUGNY',
    appId: '1:110037213358:ios:7ad8046a7de4ca032bcd3f',
    messagingSenderId: '110037213358',
    projectId: 'learningfirebase-1262f',
    storageBucket: 'learningfirebase-1262f.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAk9iusCJYEnjkKxux0gCyC4nyDntafNms',
    appId: '1:110037213358:web:f1d0d8c56b40803a2bcd3f',
    messagingSenderId: '110037213358',
    projectId: 'learningfirebase-1262f',
    authDomain: 'learningfirebase-1262f.firebaseapp.com',
    storageBucket: 'learningfirebase-1262f.appspot.com',
    measurementId: 'G-7H97J85B3B',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk9iusCJYEnjkKxux0gCyC4nyDntafNms',
    appId: '1:110037213358:web:f1d0d8c56b40803a2bcd3f',
    messagingSenderId: '110037213358',
    projectId: 'learningfirebase-1262f',
    authDomain: 'learningfirebase-1262f.firebaseapp.com',
    storageBucket: 'learningfirebase-1262f.appspot.com',
    measurementId: 'G-7H97J85B3B',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBcFwD6DXPT1ITDMv6EH3O4l2t30DUGNY',
    appId: '1:110037213358:ios:7ad8046a7de4ca032bcd3f',
    messagingSenderId: '110037213358',
    projectId: 'learningfirebase-1262f',
    storageBucket: 'learningfirebase-1262f.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

}